export const AUTHORIZATION_RISE = "AUTHORIZATION_RISE";
export const CREDENTIAL_LOADED = "CREDENTIAL_LOADED";
export const CREDENTIAL_RESET = "CREDENTIAL_RESET";
export const USER_LOADED = "USER_LOADED";
export const UNAUTHORIZATION_RISE = "UNAUTHORIZATION_RISE";